# Generated by Django 4.1.3 on 2023-10-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250)),
                ('isbn', models.CharField(max_length=13)),
                ('pengarang', models.CharField(max_length=250)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('tanggal_rilis', models.DateField()),
                ('jumlah_halaman', models.IntegerField()),
                ('gambar', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Minuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250)),
                ('isbn', models.CharField(max_length=13)),
                ('pengarang', models.CharField(max_length=250)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('tanggal_rilis', models.DateField()),
                ('jumlah_halaman', models.IntegerField()),
                ('gambar', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
