# Generated by Django 4.1.3 on 2023-10-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_makanan_minuman_toko_delete_book_delete_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Toko',
        ),
    ]
