# Generated by Django 4.1.3 on 2023-10-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_toko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makanan',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='makanan',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='minuman',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='minuman',
            name='nama',
        ),
        migrations.AddField(
            model_name='makanan',
            name='harga1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makanan',
            name='nama1',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minuman',
            name='harga2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minuman',
            name='nama2',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
