# Generated by Django 4.1.3 on 2023-10-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_makanan_harga_remove_makanan_nama_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Minuman',
        ),
        migrations.RenameField(
            model_name='makanan',
            old_name='harga1',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='makanan',
            old_name='nama1',
            new_name='nama',
        ),
    ]
