# Generated by Django 4.1.3 on 2023-10-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_delete_minuman_rename_harga1_makanan_harga_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Makanan',
            new_name='Tes',
        ),
    ]
