# Generated by Django 4.1.3 on 2023-10-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_toko_listmakanan_remove_toko_listminuman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='gambar',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minuman',
            name='gambar',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
