# Generated by Django 4.1.3 on 2023-10-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_makanan_gambar_minuman_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='deskripsi',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minuman',
            name='deskripsi',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
