# Generated by Django 4.1.3 on 2023-10-28 15:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kantin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('telpon', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='min 8 digit', regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='makanan',
        ),
        migrations.DeleteModel(
            name='Minuman',
        ),
        migrations.RenameField(
            model_name='makanan',
            old_name='stock',
            new_name='stok',
        ),
        migrations.RemoveField(
            model_name='makanan',
            name='deskripsi',
        ),
        migrations.AddField(
            model_name='makanan',
            name='TERSEDIA',
            field=models.CharField(choices=[('1', 'Tersedia'), ('0', 'Tidak tersedia')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.AddField(
            model_name='makanan',
            name='kantin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.kantin'),
            preserve_default=False,
        ),
    ]
