# Generated by Django 4.1.3 on 2023-10-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_minuman'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='TYPE',
            field=models.CharField(choices=[('1', 'Makanan'), ('0', 'Minuman')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Minuman',
        ),
    ]
