# Generated by Django 4.1.3 on 2023-10-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_makanan_type_delete_minuman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makanan',
            old_name='TYPE',
            new_name='type',
        ),
    ]
